---
# tasks file for roles/user-n01669400
- name: Create group cloudadmins
  group:
    name: cloudadmins
    state: present

- name: Create users and add them to groups
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    append: yes
    shell: /bin/bash
    state: present
  loop:
    - user100
    - user200
    - user300

- name: Generate SSH key for each user
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop:
    - user100
    - user200
    - user300

- name: Fetch private key for user100 to local machine
  fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "~/user100_id_rsa"
    flat: yes
