# roles/user-HumberID/tasks/main.yml

---
- name: Create cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Create users user100, user200, and user300
  user:
    name: "{{ item }}"
    group: cloudadmins, wheel
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "/home/{{ item }}/.ssh/id_rsa"
    ssh_key_passphrase: ""
  loop:
    - user100
    - user200
    - user300

- name: Download private key from VM1 for user100
  fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "./user100_key"
    flat: yes
  when: inventory_hostname == 'VM1'