# roles/webserver-HumberID/tasks/main.yml
---
- name: Install Apache Web Server
  yum:
    name: httpd
    state: present

- name: Create vm1.html, vm2.html, vm3.html
  template:
    src: "{{ item }}.j2"
    dest: "/home/azureuser/{{ item }}.html"
  loop:
    - vm1
    - vm2
    - vm3

- name: Copy vm files to var/www/html
  copy:
    src: "/home/azureuser/{{ item }}.html"
    dest: "/var/www/html/{{ item }}.html"
    mode: '0444'
  loop:
    - vm1
    - vm2
    - vm3

- name: Ensure Apache is started and enabled on boot
  service:
    name: httpd
    state: started
    enabled: yes
